### PR TITLE
New_structure for reference implementation

### PR DESCRIPTION
**Pull request by Polaris000**
@jgbarah, @aswanipranjal and @valeriocos: Please have a look at this quick (and rough) attempt at the new structure, as discussed in my latest [blog post](https://polaris000.github.io/blog/com_bonding_2) and the latest meeting [log](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/may_24_comm_bonding.txt).

I have added a:
-  notebook (along with the data and the metric.md file)
-  python script (generated from the notebook)
-  test file with a few tests

Please share your views regarding this implementation. Thanks :)

### CODE REVIEW

**Comment by Polaris000** [comment]
I'm merging this for now: but please add your views on this :)

**Comment by Polaris000** [comment]
@jgbarah please review this rough implementation, whenever it is convenient for you.

**Comment by aswanipranjal** [comment]
@Polaris000 sorry about not being able to reply earlier. I am going through the repo and here are a few tips:
- Fetching the data from perceval is not clear enough. You can add that part in the Notebook it self so that the user can just run the cells and get the data. OR you can add that part in the README.md for that notebook so that the user can be prepared with the data before opening the notebook. I feel that will be easier for the user to go through the notebook even. 
- The `since` and `until` variables are being set during the class initialization, but you've tried to use them with the `compute` method in the last cell, which will throw an error
- Maybe you can just get create the data frame with the data for a particular time period when you initialize the class itself? 
- You should mention the variables under the methods that you implement. Here, `since` should be under class decleration docstring rather than under the `compute` method
- Try to be consistent with what you put in the docstrings. Don't skip variables

**Comment by Polaris000** [comment]
Thanks for the reply @aswanipranjal!
Regarding your points:
- Good point! I had done this thing for the microtasks using bash snippets. Here, I just modified the existing implementation and did not add that part. 
**My query**:
Should I add that using bash scripts like I have done [here](https://github.com/Polaris000/Chaoss_19_Microtasks/blob/master/microtask0/microtask0.ipynb) or something else?


- Yes, that is just a commented part (from the old implementation). Will remove it.
**My query**:
Should the `since` and `until` parameters be passed to the class or `compute`? According to me, it seems more intuitive. Let me know what you think.

- This is in continuation to my query on the previous point. Though it is more efficient to create a dataframe for what is required, I think it is more intuitive to let the parameters to `compute` (by that I mean `since` and `until`) decide the time period. Could you tell me why you think the former (creating dataframe directly with respect to since and until) is better?

- Will do that! As mentioned, I just changed functionality of existing code, without touching comments. I did not want to finish the whole thing only to realize I was going in the wrong direction. Will make the appropriate changes now. 

- Thanks. Will do.

**Another query:** 
Should I manipulate the data fetched by Perceval to make it easier to understand in the reference implementation (using the `_summary` method) or should do we directly work with what we get from Perceval?

Please have a look at my queries. Any other feedback is welcome :). 
Thanks for the review!

**Comment by Polaris000** [comment]
I have made some changes in a recent commit so please check the notebook in master [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/Weekly_Work/Week0/Code_changes-git/Code_Changes_Git.ipynb)

**Pull request merged**
